### PR TITLE
Team 13 City Planning

### PR DESCRIPTION
**Pull request by igniteeng000**
Lokal a community chat app for local areas.

### CODE REVIEW

**Comment by igniteeng000** [comment]
Video link https://drive.google.com/file/d/1YDihikIWoVYtfyC7NyykoDTSbSaOaEiH/view?usp=sharing

**Comment by aashutoshrathi** [comment]
Add all your files inside your team folder, and please pull changes before doing so.

**Comment by aashutoshrathi** [comment]
Resolve README conflicts

**Comment by igniteeng000** [comment]
I have moved the readme file already

**Comment by aashutoshrathi** [comment]
Resolve conflicts

**Comment by aashutoshrathi** [comment]
Thanks

**Pull request merged**
